### ISSUE TITLE
Not working with IE 11

### ISSUE THREAD

**Issue by werthdavid** [odahcam/zxing-ts#1]
The problem seems to be that IE 11 doesn't support Uint8ClampedArray, which is needed in GlobalHistogramBinarizer.ts (and others).

**Comment by werthdavid** [comment]
Well actually that's a problem with the base-repo not your fork, but I thought we're gonna develop here. I'll create my own fork and make a PR to the base-repo instead

**Comment by odahcam** [comment]
We can develop here, because this fork is too different to take updates (merges) from the base-repo. So we will need to manually implement any updates from there to here.
